In [18]:
import pandas as pd
import numpy as np

# Separação das diferentes tabelas dentro da oferta e demanda

In [19]:
dictd = {
    'Fontes_Primárias': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=1, usecols='A:BB', nrows=31).transpose(),
    'Petróleo': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=39, usecols='A:BB', nrows=6).transpose(),
    'Gás_Natural': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=56, usecols='A:BB', nrows=27).transpose(),
    'Carvão_Vapor': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=90, usecols='A:BB', nrows=22).transpose(),
    'Carvão_Metalúrgico': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=121, usecols='A:BB', nrows=134-122).transpose(),
    'Energia_Hidráulica': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=142, usecols='A:BB', nrows=148-142).transpose(),
    'Energia_Eólica': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=152, usecols='A:BB', nrows=2).transpose(),
    'Energia_Solar_Fotovoltaica': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=160, usecols='A:BB', nrows=2).transpose(),
    'Energia_Solar_Térmica': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=167, usecols='A:BB', nrows=174-168).transpose(),
    'Urânio': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=178, usecols='A:BB', nrows=5).transpose(),
    'Lenha': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=190, usecols='A:BB', nrows=216-190-1).transpose(),
    'Caldo_de_Cana': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=222, usecols='A:BB', nrows=3).transpose(),
    'Melaço': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=232, usecols='A:BB', nrows=3).transpose(),
    'Bagaço_de_Cana': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=242, usecols='A:BB', nrows=254-243).transpose(),
    'Lixívia': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=260, usecols='A:BB', nrows=8).transpose(),
    'Outras_Fontes_Primárias': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=274, usecols='A:BB', nrows=9).transpose(),
    'Total_de_Fontes_Secundárias': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=291, usecols='A:BB', nrows=324-291).transpose(),
    'Derivados_de_Petróleo_e_Gás_Natural': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=328, usecols='A:BB', nrows=361-328-1).transpose(),
    'Óleo_Diesel_Total': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=367, usecols='A:BB', nrows=394-367-1).transpose(),
    'Diesel_de_Petróleo': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=404, usecols='A:BB', nrows=431-404-1).transpose(),
    'Biodiesel': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=437, usecols='A:BB', nrows=13).transpose(),
    'Óleo_Combustível': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=472, usecols='A:BB', nrows=501-472-1).transpose(),
    'Gasolina': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=509, usecols='A:BB', nrows=520-509-1).transpose(),
    'Gás_Liquefeito_de_Petróleo': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=527, usecols='A:BB', nrows=551-527-1).transpose(),
    'Nafta': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=557, usecols='A:BB', nrows=571-557-1).transpose(),
    'Coque_de_Carvão_Mineral': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=579, usecols='A:BB', nrows=594-579).transpose(),
    'Querosene': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=598, usecols='A:BB', nrows=623-598-1).transpose(),
    'Gás_de_Cidade': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=629, usecols='A:BB', nrows=648-629).transpose(),
    'Gás_de_Coqueria': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=652, usecols='A:BB', nrows=662-652-1).transpose(),
    'Eletricidade': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=668, usecols='A:BB', nrows=697-668).transpose(),
    'Carvão_Vegetal': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=701, usecols='A:BB', nrows=723-701).transpose(),
    'Álcool_Etílico_Total': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=727, usecols='A:BB', nrows=739-727-1).transpose(),
    'Álcool_Anidro': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=747, usecols='A:BB', nrows=758-747).transpose(),
    'Álcool_Hidratado': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=762, usecols='A:BB', nrows=774-762-1).transpose(),
    'Outras_Secundárias_de_Petróleo': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=780, usecols='A:BB', nrows=800-780-1).transpose(),
    'Alcatrão': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=806, usecols='A:BB', nrows=818-807).transpose(),
    'Produtos_não_Energéticos_de_Petróleo': pd.read_excel('../databases/Dados EPE/Oferta e Demanda de Energia por Fonte.xlsx', header=824, usecols='A:BB', nrows=833-824-1).transpose()
}

In [20]:
dict_oferta_demanda = {}
for i in dictd:
    df = dictd[i]

    # Reseta os índices que estavam errados
    df.reset_index(inplace=True)

    # Troca os headers
    headers = pd.Series([str(v).strip() for v in df.iloc[0].values])
    headers[0] = 'ANO'
    df.columns = headers
    df.drop(index=0, axis=0, inplace=True)

    # Reseta o indice para que 1970 seja 0
    df.reset_index(drop=True, inplace=True)

    dict_oferta_demanda[i] = df

Depois disso, ainda existem dataframes com anos sem dados, mas é possível usar um índice em comum.

In [22]:
dict_oferta_demanda['Energia_Hidráulica']

,ANO,PRODUÇÃO,CONSUMO TOTAL,TRANSFORMAÇÃO,GERAÇÃO PÚBLICA,GERAÇÃO DE AUTOPRODUTORES
0,1970,39801.0,39801.452899,39801.452899,38414.0,1387.452899
1,1971,43199.0,43198.608696,43198.608696,41867.0,1331.608696
2,1972,50681.0,50680.855072,50680.855072,49237.0,1443.855072
3,1973,57890.0,57890.376812,57890.376812,56290.0,1600.376812
4,1974,65679.0,65678.717391,65678.717391,63981.0,1697.717391
5,1975,72287.0,72287.173913,72287.173913,70387.0,1900.173913
6,1976,82913,82913,82913,80682,2231
7,1977,93480,93480,93480,90883,2597
8,1978,102746,102746,102746,99996,2750
9,1979,116580,116580,116580,113952,2628
10,1980,128907,128907,128907,126104,2803
11,1981,130765,130765,130765,128095,2670
12,1982,141132,141132,141132,138432,2700
13,1983,151475,151475,151475,148503,2972
14,1984,166593,166593,166593,163552,3041
15,1985,178375,178375,178375,175334,3041
16,1986,182419,182419,182419,178991,3428
17,1987,185600,185600,185600,182105,3495
18,1988,199093,199093,199093,195547,3546
19,1989,204690,204690,204690,201104,3586
20,1990,206708,206708,206708,203594,3114
21,1991,217782,217782,217782,214609,3173
22,1992,223343,223343,223343,220583,2760
23,1993,235065,235065,235065,231695,3370
24,1994,242705.0,242705.1,242705.1,239467.0,3238.1
25,1995,253905.0,253905.1,253905.1,250456.0,3449.1
26,1996,265769.0,265735.8,265735.8,261445.0,4290.8
27,1997,278972.0,278972.506396,278972.506396,274586.0,4386.506396
28,1998,291469.0,291469.18,291469.18,286358.0,5111.18
29,1999,293000.0,293000.0306,293000.0306,287317.0,5683.0306
30,2000,304403.0,304403.275984,304403.275984,298563.0,5840.275984
31,2001,267876,267876,267876,262665,5211
32,2002,286092.0,286092.2,286092.2,274338.0,11754.2
33,2003,305616,305616,305616,294274,11342
34,2004,320796.906836,320796.906836,320796.906836,308584.0,12212.906836
35,2005,337456.574863,337456.773014,337456.773014,325052.9358,12403.837214
36,2006,348805.46,348805.46,348805.46,335761.0,13044.46
37,2007,374015.1216,374015.1216,374015.1216,359256.31,14758.8116
38,2008,369556.4,369556.4,369556.4,354285.0,15271.4
39,2009,390988.065,390988.065,390988.065,371670.0,19318.065
40,2010,403289.813262,403289.813262,403289.813262,382599.352443,20690.460819
41,2011,428332.919871,428332.919871,428332.919871,405620.88571,22712.034161
42,2012,415342.175457,415342.175457,415342.175457,394879.392523,20462.782933
43,2013,390992.013974,390992.013974,390992.013974,368938.82036,22053.193614
44,2014,373439.060474,373439.060474,373439.060474,351350.866167,22088.194307
45,2015,359742.808194,359742.808194,359742.808194,338672.92264,21069.885554
46,2016,380910.94238,380910.94238,380910.94238,359499.162393,21411.779987
47,2017,370906.456376,370906.456376,370906.456376,352313.432802,18593.023574
48,2018,388971.075877,388971.075877,388971.075877,369640.904836,19330.171042
49,2019,397877.056629,397877.056629,397877.056629,378449.614595,19427.442034
50,2020,396381.195389,396381.195389,396381.195389,378636.583319,17744.61207
51,2021,362818.451095,362818.451095,362818.451095,346816.102854,16002.348241
52,2022,427113.549289,427113.549289,427113.549289,406652.543017,20461.006272